### ISSUE TITLE
Potential error in a string from train 60

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa-content-server-l10n#118]
I’m almost positive a ’s’ is missing here https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/en_US/LC_MESSAGES/client.po#L448
@shane-tomlinson , do you confirm?

**Comment by shane-tomlinson** [comment]
@TheoChevalier - Oh no, thank you so much for noticing!

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/commit/c4a85c80290a96b559e7e04d62077efd6097cd21 update to `.po` coming up

**Comment by TheoChevalier** [comment]
Thanks guys!
