### ISSUE TITLE
Missing number of times in string

### ISSUE THREAD

**Issue by mohamed7afezz** [mozilla/fxa-content-server-l10n#123]
All this stings in this [link](https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/ar/LC_MESSAGES/client.po#L115-L143) need to update with some Details because We in Arabic language we need to know number of times of thing like:
- "days ago" string should be "%S days ago" 
- "hours ago" string should be "%S hours ago"

so we can translate it by adding number of days in middle "منذ %S يومًا" but without we can't translate them.

*this way already use in other projects, check this strings in [transvision](https://transvision.mozfr.org/?sourcelocale=en-US&locale=ar&repo=release&search_type=entities&recherche=toolkit/chrome/places/places.properties:finduri-AgeInDays-is)

**Comment by vladikoff** [comment]
> "days ago" string should be "%S days ago"
> "hours ago" string should be "%S hours ago"

We are not adding numbers at this time. The translation should not specify %s.

Are you able to just translate `days ago`? 

For example can you translate: `I had to buy a new cake days ago` or `The train to the city left hours ago"?

**Comment by mohamed7afezz** [comment]
Yup, thanks.
