### ISSUE TITLE
grunt l10n-lint fails

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server-l10n#158]
> grunt l10n-lint --verbose
....
> Reading locale/templates/LC_MESSAGES/client.pot...OK
> Reading locale/templates/LC_MESSAGES/messages.pot...OK
> Warning: Cannot convert undefined or null to object Use --force to continue.

This occurs using node 4. Also fails on travis: https://travis-ci.org/mozilla/fxa-content-server-l10n/jobs/172871222

**Comment by vladikoff** [comment]
hm works for me with node 4.6.1

**Comment by TDA** [comment]
Master seems to work on:
```
node -v
v4.4.4
npm -v
2.14.22
os x 10.11.6
```

Not sure if required but seems to work fine on:
```
npm -v
2.4.1
node -v
v0.10.38
```
Tried to run it with node v6, but it said `grunt: command not found` and I have no idea how to get that to work. 🐑

**Comment by shane-tomlinson** [comment]
Fails for me locally using node 0.10 and node 4, also failing on travis with node 4 - https://travis-ci.org/mozilla/fxa-content-server-l10n/jobs/173683178

**Comment by shane-tomlinson** [comment]
Huh, I had an empty generated file, `messages.pot` that was [ignored via .gitignore](https://github.com/mozilla/fxa-content-server-l10n/blob/f282928cc03930ff7f5cc252c4c5160bbc252738/locale/templates/LC_MESSAGES/.gitignore#L3) which was causing the blowup.

Maybe we should only ignore client.pot and server.pot, that way we easily see if extra files are lying around.

**Comment by TDA** [comment]
@shane-tomlinson Not sure IIRC, but did we not have something to convert empty spaces into `''` or something similar? 
Sorry if this is unrelated 🐒
