### ISSUE TITLE
Set protected status on production branch

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/fxa-content-server-l10n#272]
The production branch on this repository is not protected against force pushes. This setting is recommended as part of [Mozilla's Guidelines][guidelines_url] for a Sensitive Repository.

**Anyone with admin permissions for this repository can correct the setting using [this URL][protect_url].**

If you have any questions, or believe this issue was opened in error, please contact [us][email] and mention SOGH0001 and this repository.

Thank you for your prompt attention to this issue.
--Firefox Security Operations team

[guidelines_url]: https://wiki.mozilla.org/GitHub/Repository_Security
[protect_url]: https://github.com/mozilla/fxa-content-server-l10n/settings/branches
[email]: <mailto:secops+github@mozilla.com?subject=SOGH0001+Question+re+mozilla/fxa-content-server-l10n>

**Comment by shane-tomlinson** [comment]
This is going to take a bit of process change because pontoon commits directly to master. Each merge then kicks off a travis test, which notifies us via email whenever there is a failure.

**Comment by shane-tomlinson** [comment]
@mathjazz - can Pontoon commit to a branch other than master? I'm trying to think of what options we have here are.

**Comment by mathjazz** [comment]
Yes, it can. We just need to set the Branch in the Project Admin:
https://mozilla-l10n.github.io/documentation/tools/pontoon/adding_new_project.html

**Comment by hwine** [comment]
@shane-tomlinson flipping this bit does not prevent you from committing to master -- it just keeps you from doing force pushes.

If you're doing force pushes to master, you can instead merge to master using the merge strategy "ours". (Which also preserves history.)

**Comment by vladikoff** [comment]
Exactly, we just disable force pushes, no need to change anything in the process

**Comment by shane-tomlinson** [comment]
> Exactly, we just disable force pushes, no need to change anything in the process

'Aight, branch protection enabled without requiring pull-requests. Closing as fixed.
