### ISSUE TITLE
English translation appears in Verbatim but not in the repo

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server-l10n#32]
This string should have a translation of "to continue to %(serviceName)s", made specefically for `en_US` in Verbatim, but it shows up empty in the po file: https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/en_US/LC_MESSAGES/client.po#L619

**Comment by zaach** [comment]
@mathjazz Any idea why the translation is not being carried over to github?

**Comment by mathjazz** [comment]
@zaach The translation in Verbatim is submitted for en (not en-US):
https://localize.mozilla.org/en/accounts/translate.html#filter=translated

And it's also available in the en repository:
https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/en/LC_MESSAGES/client.po#L619

**Comment by zaach** [comment]
Doh, I could've sworn it was `en-US` in verbatim. Thanks!
