### ISSUE TITLE
Localized content not seen on staging

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa-content-server-l10n#322]
@shane-tomlinson The issue was brought up in issue https://github.com/mozilla/fxa-content-server-l10n/issues/320. Though the issue resolved some problems, however, it is not the issue that localizer @jordis brought up.

**Comment by shane-tomlinson** [comment]
Can you help me understand the problem better? I'm still confused, I think expectations might not match the reality of how the l10n import process works. 

When you say "staging" what server does that correspond to? Staging might mean something very different to us.

The translations on https://stage.dev.lcip.org are updated once every 2 weeks. The translations on https://stable.dev.lcip.org are updated once a week, on Thursday at 4pm PST. The translations on  https://latest.dev.lcip.org are updated whenever a PR is merged into the content server. String updates from Pontoon are *only* pulled in and displayed on https://latest.dev.lcip.org after a PR is merged into the content server, this is not done automatically when strings on Pontoon are updated.

As far as [https://latest.dev.lcip.org not showing translations at all](https://github.com/mozilla/fxa-content-server-l10n/issues/320#issuecomment-458945661), I do most of my development/testing in Spanish to help flag l10n issues early - this is what I see there:

<img width="655" alt="screenshot 2019-02-01 at 11 17 31" src="https://user-images.githubusercontent.com/848085/52120033-031d5980-2613-11e9-90bf-41b334f5072f.png">

Which locale is @jordis testing? It could be that we have not enabled that locale.

**Comment by peiying2** [comment]
@jordis is the locale manager for Catalan or ca.

**Comment by shane-tomlinson** [comment]
I should have known this from the link to the translations in the original bug, https://pontoon.mozilla.org/ca/firefox-accounts/. I am sorry I did not catch this earlier.

**Comment by peiying2** [comment]
Thank you so much @shane-tomlinson. Looks like a simple fix from l10n perspective.
