### ISSUE TITLE
Arabic String need translation for FFOS 2.2

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server-l10n#33]
Firefox OS 2.2 will be supporting Arabic strings. In conjunction with this push, FxA needs to localize into Arabic. If at all possible, we'd love to do this by the end of March so we can test UI layout in Arabic. 

@mathjazz, is Arabic localization reasonable in this time frame? Thanks!

**Comment by shane-tomlinson** [comment]
@johngruen - Is FxA on FxOS being translated simultaneously?

**Comment by johngruen** [comment]
@shane-tomlinson: Yes, they have their own translation process in place.

**Comment by johngruen** [comment]
@shane-tomlinson: additionally they're doing internal UI reviews etc.

**Comment by mathjazz** [comment]
Hi John, I'm pinging the Arabic community... Will report back as soon as I hear from them.

**Comment by johngruen** [comment]
Awesome, thanks!

On Wednesday, February 18, 2015, Matjaž Horvat <notifications@github.com>
wrote:

> Hi John, I'm pinging the Arabic community... Will report back as soon as I
> hear from them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/fxa-content-server-l10n/issues/33#issuecomment-74961682>
> .
>


-- 
John Gruen
web: johngruenprojects.com
general: john.gruen@gmail.com
work: jgruen@mozilla.com
phone: 401.743.8544

**Comment by rfk** [comment]
According to https://localize.mozilla.org/ar/accounts/ there's not much progress on Arabic translation; @johngruen is this bug still revelant?

**Comment by vladikoff** [comment]
@johngruen ping

**Comment by vladikoff** [comment]
@johngruen closing unless someone needs this
