### ISSUE TITLE
Merging locales bn-BD and bn-IN to single locale bn

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa-content-server-l10n#358]
We are going to merge the two locales into one to fully utilize the community resources.  The plan is:

Dev:
* FxA creates an bn folder at repo
* Move bn-BD repo content to bn repo and confirm it's all there (bn-BD has more content in comparison)
* Remove bn-BD, bn-IN repos

Pontoon (l10n);
* Pontoon dev migrates the data to bn (this includes contributors histories)
* L10n PM confirms the update and closes this issue.

@shane-tomlinson let me know if you are the person to speak about how to carry out this task.

**Comment by shane-tomlinson** [comment]
Hi @peiying2, sorry for the delay responding here. I am the person to speak to. This all seems fine to me. I just opened #359 with the `bn` directory with both files as blank templates.

**Comment by peiying2** [comment]
@shane-tomlinson I updated the issue summary after speaking to my colleague on the best way to do this. 

Could you **move** `bn-BD` to `bn` repo? After confirming it is done correctly, you can remove the bn-BD and bn-IN repos. Then Pontoon dev will migrate the data to bn. After that is done, I will close the issue.

**Comment by shane-tomlinson** [comment]
@peiying2 I have updated the `bn` directory to have the same contents as `bn-BD`. I can remove the `bn-BD` and `bn-IN` directories once you confirm the time is right.

**Comment by peiying2** [comment]
@shane-tomlinson you can remove both locales now. Right now is a good time. Thx

**Comment by peiying2** [comment]
@shane-tomlinson, make sure to correct the charset at the beginning of the file to `bn`. I got an error message from your copy.

**Comment by peiying2** [comment]
@shane-tomlinson we have completed the tasks on Pontoon side. Please make sure the bn-* repos are removed. I still see them in the locale folder. Please confirm that this is done, so we can close the issue. Thanks!

**Comment by shane-tomlinson** [comment]
> Please make sure the bn-* repos are removed. I still see them in the locale folder. 

Once the FxA config changes are complete, I will remove the extra repos.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa/pull/1870
