### ISSUE TITLE
Same string reused in different (cap or lower) case may break code

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa-content-server-l10n#423]
I might be wrong, but you're taking original translations starting with  uppercase, and reusing them after making them lowercase via JS.
https://github.com/mozilla/fxa/blob/07cefc18148d0b17f5240120a84fe151a5032088/packages/fxa-content-server/app/scripts/models/support-form.js#L15

That is incredibly fragile (I'd go as far as to say it's broken):
- JS might not be able to manage the correct transformation for locales.
- You don't know what capitalization a language should use in the middle of a sentence.
- In the middle of a sentence it might need a different case.

_Originally posted by @flodolo in https://github.com/mozilla/fxa-content-server-l10n/pull/420_

**Comment by chenba** [comment]
Fixed in https://github.com/mozilla/fxa/pull/7602.
