### ISSUE TITLE
German subscription cancellation email translation contains extra '$' (USD currency symbol)

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa-content-server-l10n#428]
(Sorry, I'm not sure if this is the correct way of reporting this.  Let me know if not, and I'll file elsewhere.)

https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/de/LC_MESSAGES/server.po#L355

The '$' in `... %(invoiceTotal)s $ ...` is not necessary since `invoiceTotal` itself is localized with a currency symbol.

(I'm aware of comments for .pot files.  Unfortunately, at the moment there's no simple way to add them for the email templates in fxa-auth-server, from where the emails are sent.)

**Comment by peiying2** [comment]
@clouserw

**Comment by peiying2** [comment]
> (Sorry, I'm not sure if this is the correct way of reporting this. Let me know if not, and I'll file elsewhere.)
> 
> https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/de/LC_MESSAGES/server.po#L355
> 
> The '$' in `... %(invoiceTotal)s $ ...` is not necessary since `invoiceTotal` itself is localized with a currency symbol.
> 
> (I'm aware of comments for .pot files. Unfortunately, at the moment there's no simple way to add them for the email templates in fxa-auth-server, from where the emails are sent.)

Here is the source string: `Your final payment of %(invoiceTotal)s was paid on %(invoiceDateOnly)s. `

There is no $ sign in the English source. Should I remove $ in German and that would fix it?

**Comment by clouserw** [comment]
Thanks @peiying2 .  Yes, that should fix it.  I'll leave for @chenba to close this out.

**Comment by chenba** [comment]
Looks good.  Thanks!
