### ISSUE TITLE
Partial translation not displayed in Support page 

### ISSUE THREAD

**Issue by petercpg** [mozilla/fxa-content-server-l10n#430]
URL: https://accounts.stage.mozaws.net/support
Locale: zh-TW
Screenshot: ![圖片](https://user-images.githubusercontent.com/205738/86532258-2250a280-befb-11ea-9179-add672eb6741.png)

The strings missed for translation already exists in https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/zh_TW/LC_MESSAGES/client.po#L418 . Maybe need an update for string id reference?

**Comment by peiying2** [comment]
Thank you for reporting this issue. The Contact Us or the support feature will not be ready until billing and subscription management features are complete. Contact Us feature involves staffing people who can answer questions in languages in the supported markets.  This is why the test step instruction for the first feature ends when you get a subscription confirmation. Anything beyond is not set up in the test  server for all languages at the moment.

**Comment by chenba** [comment]
Fixed in https://github.com/mozilla/fxa/pull/7602.
