### ISSUE TITLE
Ligatures in client.po files

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server-l10n#45]
Per https://github.com/mozilla/fxa-content-server/pull/2244

We removed a weird ligature in [mozilla/**fxa-content-server**](https://github.com/mozilla/fxa-content-server/)'s [app/scripts/templates/change_password.mustache](https://github.com/mozilla/fxa-content-server/blob/8cf5c9356bc7d8735bed5c1dd851e3b5d6b65fe0/app/scripts/templates/change_password.mustache#L12) template (from `ﬁnished` to `finished`).

We still have the ligatures in the keys for all these locales in this repo (see [fr's client.po file](https://github.com/mozilla/fxa-content-server-l10n/blob/a8c9d0d24d3774e0a7a2c0b7bd1a65c1ac948a21/locale/fr/LC_MESSAGES/client.po#L401)). Not sure if we need to search/replace or copy/paste and add new translations for the ligature and non-ligature versions, or if these strings will just stop displaying translated values once we push out the new fxa-content-server code.

**Comment by mathjazz** [comment]
Interesting. Yeah, we should change the keys for all locales with a script and then merge and update Verbatim.

**Comment by pdehaan** [comment]
Closing. I think this was expertly fixed months ago.
