### ISSUE TITLE
Paypal should be PayPal; a brand name should be a placeable

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa-content-server-l10n#471]
File: main.ftl
Problem: Paypal should be treated like a brand name, a placeable, and should be spelled correctly - capital Ps. 

[## payment legal blurb](https://github.com/mozilla/fxa-content-server-l10n/blob/e63e272543278913fbb134dc47be7660446dd222/locale/templates/main.ftl#L78-L80)
payment-legal-copy-stripe-paypal = { -brand-name-mozilla } uses Stripe and Paypal for secure payment processing.
payment-legal-link-stripe-paypal = View the <stripePrivacyLink>Stripe privacy policy</stripePrivacyLink> and <paypalPrivacyLink>Paypal privacy policy</paypalPrivacyLink>.

After the release of the settings.ftl, let's standardize the treatment of these brand names.

@chenba

**Comment by clouserw** [comment]
This will appear in this repository next Friday.  Thanks
