### ISSUE TITLE
The string for *None* needs to be duplicated for different setting scenarios

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa-content-server-l10n#472]
File: settings.ftl
Problem: The string `None` is used in settings for both *Primary email* and *Secondary email*. In some languages, these two have two separate genders associated with them, thus `None` will be translated differently.

[row-defaults-status = None](https://github.com/mozilla/fxa-content-server-l10n/blob/f9fd8c07866f9df13f67b431978241de8b1f3e51/locale/templates/settings.ftl#L379)

Suggestion: Add another string for None, one for each of the emails, with detailed comments/or string ID name so localizers know where the word is used.

Fixes include new IDs.

@chenba

**Comment by chenba** [comment]
@6a68 can you take a look?  Thanks!

**Comment by 6a68** [comment]
This one might take a little longer to get to, because it involves some deeper changes to how the code is structured.

**Comment by 6a68** [comment]
I've copied this over to the FxA repo for better visibility

**Comment by peiying2** [comment]
> I've copied this over to the FxA repo for better visibility

Any update on this?
