### ISSUE TITLE
Spelling error, brand tagging, ellipsis

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa-content-server-l10n#480]
A few errors have been identified from PR https://github.com/mozilla/fxa-content-server-l10n/pull/479:
1).  [main.ftl](https://pontoon.mozilla.org/en-CA/firefox-accounts/main.ftl/?string=220953): Should be  **occurred** in`An unexpected error has *occured* while processing your payment, please try again`

2). [main.ftl]: add **Stripe** as a brand name on the top of the file so these strings can be tagged correctly like other third party brands: https://github.com/mozilla/fxa/blob/0ab97ffd95721127890d27167a6404a60d4af2ab/packages/fxa-payments-server/public/locales/en-US/main.ftl#L89-L97

3). Ellipsis vs 3 periods: there are a few strings in the PR, but periods are used in place for Ellipsis. 
a). [Confirming subscription...](https://pontoon.mozilla.org/en-CA/firefox-accounts/main.ftl/?string=220945) 
b). [Error confirming subscription...](https://pontoon.mozilla.org/en-CA/firefox-accounts/main.ftl/?string=220935) 
c). [Please wait while we process your payment...](https://pontoon.mozilla.org/en-CA/firefox-accounts/main.ftl/?search=process+your+payment&string=220947) 
d). [Updating billing information...](https://pontoon.mozilla.org/en-CA/firefox-accounts/main.ftl/?search=...&string=212104) 

NOTE: 
- Numbers 1 + 2 require new string IDs.
- Number 3 can keep the same ID. We hope the communities use ellipsis when translating the strings. These hopefully only impact en-CA and en-GB locales, but hopefully they update these when leveraging them.

**Comment by peiying2** [comment]
@6a68 please help triage. Thank you.

**Comment by 6a68** [comment]
Sure, I can fix these, thanks for the ping

**Comment by 6a68** [comment]
@peiying2 The fixes for this issue should arrive in today's export. Let me know if any other changes are needed. Thanks!

**Comment by peiying2** [comment]
> @peiying2 The fixes for this issue should arrive in today's export. Let me know if any other changes are needed. Thanks!

Thank you. I have approved and merged the weekly PR. Thank you for the timely fixes.
