### ISSUE TITLE
Was change from 'Language: pt_BR' to 'Language: pt-BR' correct?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server-l10n#52]
See this comment in https://github.com/mozilla/fxa-auth-mailer/pull/46#issuecomment-111657709

In https://github.com/mozilla/fxa-content-server-l10n/commit/c26368b674cd1335a73b53c33b6da4bae78de68f, the `Language:` header was changed from `pt_BR` to `pt-BR`, which is unlike all the other country-specific locales in this repository. Was that a correct change? Can they be used interchangeably? 

(Of course, crashing on this change is a bug in the fxa-auth-mailer, for any inputs).

**Comment by vladikoff** [comment]
cc @mathjazz

**Comment by jrgm** [comment]
So I fixed the code in mozilla/fxa-auth-mailer so it handles either form. And perhaps the answer on this issue is that either form is valid (but it does feel random).

**Comment by mathjazz** [comment]
This is another locale switching to Pontoon.

**Comment by mathjazz** [comment]
Hotfix landed in Pontoon:
https://github.com/mozilla/fxa-content-server-l10n/commit/ee79552c1139d1b10b86a4e407bccc520cf90279

**Comment by vladikoff** [comment]
Should be fixed when this is getting deployed.
