### ISSUE TITLE
FxA Settings en-CA locale contains paragraph characters

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/fxa-content-server-l10n#523]
When accessing FxA settings, my locale is en-CA and it appears to contain a bunch of those paragraph/pilcrow characters. They are visible in production.

I can see them in the file: https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/en_CA/settings.ftl#L122

![Screen Shot 2021-10-05 at 2 54 43 PM](https://user-images.githubusercontent.com/6392049/136076882-e528ead3-152f-4b33-9298-d47a6c00684a.png)
![Screen Shot 2021-10-05 at 2 48 54 PM](https://user-images.githubusercontent.com/6392049/136076883-4b5dfe5d-526f-4686-be62-f22db493a621.png)

**Comment by clouserw** [comment]
The linked issue is closed as fixed.  Closing this as well.
