### ISSUE TITLE
Link id and href changed in zh_CN translation

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server-l10n#55]
In [./locale/zh_CN/LC_MESSAGES/client.po:661-671](https://github.com/mozilla/fxa-content-server-l10n/blob/2bd08a598947d8c4ac2da20f2a86bede3e02f878/locale/zh_CN/LC_MESSAGES/client.po#L661-L671) there may be some invalid translations:

```po
#: app/scripts/templates/force_auth.mustache:9
#: app/scripts/templates/sign_in.mustache:25
#: app/scripts/templates/sign_up.mustache:13

msgid ""
"By proceeding, you agree to the <a id=\"fxa-tos\" href=\"/legal/terms"
"\">Terms of Service</a> and <a id=\"fxa-pp\" href=\"/legal/privacy\">Privacy "
"Notice</a> of Firefox cloud services."

msgstr ""
"继续提交即代表您同意 %(serviceName)s (%(serviceUri)s) 的 <a id=\"service-tos"
"\" href=\"%(termsUri)s\">服务条款</a>和<a id=\"service-pp\" href="
"\"%(privacyUri)s\">隐私声明</a>。"
```

It looks like the `id` attributes got switched from `fxa-tos` to `service-tos` and `fxa-pp` to `service-pp`.
Similarly, it looks like the URLs may have been changed slightly:

| en_US | zh_CN |
|----|----|
| `fxa-tos` | `service-tos` |
| `fxa-pp` | `service-pp` |
| `href="/legal/terms"` | `href="%(termsUri)s"` |
| `href="/legal/privacy"` | `href="%(privacyUri)s"` |

There are also `%(serviceName)s` and `%(serviceUri)s` strings in the **zh_CN** translation which I don't see in **en_US**.

**Comment by yfdyh000** [comment]
https://github.com/mozilla/fxa-content-server-l10n/commit/fceb086f0b5369b754cfb540e7f1816a8d4db2c7 fixed?

p.s. https://bugzilla.mozilla.org/show_bug.cgi?id=1179883 need for attention.

**Comment by vladikoff** [comment]
Changing the IDs will not be allowed.
