### ISSUE TITLE
Change repository base branch name from 'master' to 'main'

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa-content-server-l10n#566]
A couple of years ago, FxA changed its base branch name, as well as fxa-private's, from `master` to `main`. I was reminded in recent training that we should move away from using terms like `master` and am advocating we at least update our ecosystem-docs repo to follow suite.

I know this repo is tied to Pontoon and there may be additional steps to make that happen here. I'm curious what the level of effort would be for this and the best way to communicate the change out to those that should know about it.

**Comment by flodolo** [comment]
> I know this repo is tied to Pontoon and there may be additional steps to make that happen here. I'm curious what the level of effort would be for this and the best way to communicate the change out to those that should know about it.

It's minimal. We need to stop sync for the project, rename the branch here, and restart sync.

I can do it at any point, if it doesn't require specific work on the FxA code side.

**Comment by flodolo** [comment]
Note: I see mentions of "master" in scripts and README, so they definitely need updates.

**Comment by flodolo** [comment]
Actively working on this.

I've already fixed the l10n side of things (this repo and Pontoon). To complete, we need:
* This [pull request](https://github.com/mozilla/fxa/pull/13778) merged in FxA
* Remove the master branch here (which is already set as non-default branch)
