### ISSUE TITLE
Drop sr-Latn?

### ISSUE THREAD

**Issue by flodolo** [mozilla/fxa-content-server-l10n#576]
That was a language that we used for Firefox OS, and it was generated automatically from Serbian (Cyrillic). 

Is there anything generating that now? I'm asking, because my linter caught an error in `verificationReminderFirst-description`(auth.ftl), and that was fixed a month ago in [Serbian](https://pontoon.mozilla.org/sr/firefox-accounts/auth.ftl/?search=erificationReminderFirst-description&string=235641).

**Comment by flodolo** [comment]
@clouserw 
Putting this on the radar ;-)

**Comment by clouserw** [comment]
Thanks for the ping.  I think we generate this at https://github.com/mozilla/fxa-content-server-l10n/blob/master/scripts/extract_strings.sh#L86 

Good to know we can drop it, I'll think on if there is anywhere else we reference it.

**Comment by flodolo** [comment]
Ah, the translation was submitted 1 month ago, but only approved 8 days ago
https://github.com/mozilla/fxa-content-server-l10n/commit/c0173e59b54b2f3bbce04549ec020280a97fe629

That's why it's not showing up as fixed yet.

Still, I don't think there's value in keeping it around at this point.

**Comment by flodolo** [comment]
Having now more knowledge of the extraction process, I think that we really should remove this locale.

The process only transliterate the po file via `msgfilter`, there is nothing doing that for the FTL bits.

**Comment by flodolo** [comment]
@clouserw 
Do we have any data on how many users end up on the sr-Latn pages, in absolute numbers and compared to standard `sr`? If the number is particularly high, we should add conversion for FTL files, if not we should drop it completely.

**Comment by clouserw** [comment]
For the past 30 days `sr` gets about 5-6k hits/day.  `sr-LATN` gets between 0 and 1 per day.
