### ISSUE TITLE
Unexpected link in the content server

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server-l10n#58]
This link should not be in the po file: 
https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/zh_CN/LC_MESSAGES/client.po#L116

@mathjazz We are going to be removing the link from this repo, do we also need to update this somewhere else?

**Comment by mathjazz** [comment]
It has to be fixed in Verbatim, too. I can fix it and commit to repository. What should the new translation be?

**Comment by vladikoff** [comment]
@mathjazz You can fix it if you want / have time. Currently it is: 

```
# see https://bugzilla.mozilla.org/show_bug.cgi?id=1131472
#: app/scripts/views/reset_password.js:74 app/scripts/views/sign_in.js:175
msgid "Unknown account. <a href=\"/signup\">Sign up</a>"
msgstr ""
"未知账号（<a href=\"http://firefox.com.cn/help/accounts/unknown/\">中国区帮助"
"</a>）。<a href=\"/signup\">注册</a>"
```

change it to


```
#: app/scripts/views/reset_password.js:74 app/scripts/views/sign_in.js:175
msgid "Unknown account. <a href=\"/signup\">Sign up</a>"
msgstr ""
"未知账号 <a href=\"/signup\">注册</a>"
```

cc @jrgm 

There is that bug comment but we cannot allow this link for security reasons.

**Comment by mathjazz** [comment]
Fixed:
https://github.com/mozilla/fxa-content-server-l10n/commit/03ca1b08da66ec57824c8a6c677b2f984c6a8925

**Comment by vladikoff** [comment]
Thanks so much @mathjazz !
