### ISSUE TITLE
Move Grunt XSS tasks to the l10n repo

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server-l10n#61]
Per @vladikoff's https://github.com/mozilla/fxa-auth-mailer/issues/67#issuecomment-125216940

> _if the "full" templates live in the l10n repo then we should probably move those XSS parse tasks out of the content server and put them into the l10n repo_

**Comment by pdehaan** [comment]
It'd also be nice to add some Travis-CI magic to this repo, so the Grunt tasks get automatically run on each commit.

**Comment by vladikoff** [comment]
yeaaa!

**Comment by vladikoff** [comment]
We discussed this in the meeting that this is not on track for this trian, removed from "in progress"
