### ISSUE TITLE
Cannot update to 'hi'/'hi-IN' for fxa-auth-server - missing locale.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server-l10n#65]
Please see https://github.com/mozilla/fxa-auth-server/pull/1019 and https://travis-ci.org/mozilla/fxa-auth-server/jobs/75789764.

I was trying to update to get `hi` translations for email messages, but it fails because `OperationalError: ENOENT, lstat '/Users/jrgm/tmp33/fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/fxa-content-server-l10n/locale/hi'`

I can "fix" this by manually copying `fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/fxa-content-server-l10n/locale/hi-IN` to `fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/fxa-content-server-l10n/locale/hi-IN`, and editing `fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/fxa-content-server-l10n/locale/hi/LC_MESSAGES/server.po` to set `Language:` to `hi`. Um, obviously?

There are 3 wildcard domains, in fxa-content-server-l10n:
  1. `sr`/`sr_Latn` where sr_Latn is, I think, a mechanical translation of Cyrillic to Latin alphabet.
  2. `sv`/`sv_SE` where they seem to be independent locales.
  3. hi-IN where there is no corresponding `hi`.

Can we figure out a way to treat these consistently?

**Comment by zaach** [comment]
Right, so we currently copy the files between locales in the content-server, but that of course doesn't help other repos relying on these locales. symlinks in the l10n repo might be a better option.

**Comment by rfk** [comment]
The commit adding the copying behaviour for hi-IN => hi, for reference:

  https://github.com/mozilla/fxa-content-server/commit/c45edce

**Comment by rfk** [comment]
@jrgm what do you think about me adding a build script to this repo, that would take care of these sorts of things:

* copying `hi-IN` => `hi`
* creating `sr_Latn` from `sr`
* and maybe even making train-related tags for commits that are being sent to production?

Not sure how well this would fit into your workflow, but it seems sensible to centralize those steps in this repo rather than managing it in dependant repos as done in mozilla/fxa-content-server@c45edce

**Comment by rfk** [comment]
Assigning to @jrgm for comment on the above proposal

**Comment by vladikoff** [comment]
We are going to try solve this with https://github.com/mozilla/fxa-content-server-l10n/issues/81#issuecomment-153783912
