### ISSUE TITLE
Fuzzy translations on live

### ISSUE THREAD

**Issue by piotrdrag** [mozilla/fxa-content-server-l10n#73]
Currently strings marked as "fuzzy" are used on the live web pages. In case a translation is out of date, it makes invalid translations to show up instead of English. For example, right now it says "Konto zostało zweryfikowane" ("Verified account") instead of "Account picture" on Polish pages. It's very confusing to users. "Fuzzy" strings in the PO file format are not supposed to be used: <https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html#Fuzzy-Entries>.

**Comment by shane-tomlinson** [comment]
Two possible solutions spoken about:

1. fuzzy strings should not be in the .po files in the first place, so perhaps our po merge script has gone bonkers.
1. fuzzy strings should be ignored by our grunt-po2json script.

**Comment by shane-tomlinson** [comment]
@piotrdrag - are the fuzzy strings presented to users or just to translators?

**Comment by piotrdrag** [comment]
> 1. fuzzy strings should not be in the .po files in the first place, so perhaps our po merge script has gone bonkers.
> 2. fuzzy strings should be ignored by our grunt-po2json script.

Fuzzy strings belong to the po files, but shouldn't be used. The second option sounds like the Right Thing™.

> @piotrdrag - are the fuzzy strings presented to users or just to translators?

They are presented to the end-users. :(

**Comment by vladikoff** [comment]
![](http://v14d.com/i/560973fccc68d.jpg)


cc @mathjazz

**Comment by mathjazz** [comment]
What @piotrdrag said. :)

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/3114

**Comment by zaach** [comment]
Ref https://github.com/mozilla/fxa-content-server-l10n/pull/29, where we turned of fuzzy matching on msgmerge.
