### ISSUE TITLE
Automatically copy/symlink "pt-PT" to "pt"

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server-l10n#81]
For the reasons described in https://github.com/mozilla/fxa-content-server-l10n/pull/79#issuecomment-150574399

**Comment by vladikoff** [comment]
Need to copy it the same way as here: thhttps://github.com/mozilla/fxa-content-server/blob/master/grunttasks/copy.js#L86

**Comment by vladikoff** [comment]
to clarify it is `pt_PT`, not `pt-PT` https://github.com/mozilla/fxa-content-server-l10n/tree/master/locale/pt_PT/LC_MESSAGES

**Comment by shane-tomlinson** [comment]
Re-opening until we have an answer to [this question in the PR](https://github.com/mozilla/fxa-content-server/pull/3224#issuecomment-151771972):

> @rfk and I had a discussion yesterday where he mentioned this same work needs to be done on the auth-mailer. All of our copy from one locale to another shenanigans do. Is this true Ryan?

**Comment by vladikoff** [comment]
After discussing in a meeting it seems @shane-tomlinson has a plan to solve this in the l10n repo. Let me know if help needed

**Comment by rfk** [comment]
There's enough open l10n quality issues that I spun up a (hopefully short-lived) milestone to collect them all together.  I'm grouping this together with the others in "now" for discussion as a whole in the upcoming cycle.

**Comment by mathjazz** [comment]
We need to do the same thing for Punjabi. Localizers will commit to pa_IN and pa should have the same content.

**Comment by vladikoff** [comment]
After meeting, we are gonna update out merge script to copy sv_SE to sv, hi_IN to hi, pt_PT to pt when we cut string : https://github.com/mozilla/fxa-content-server-l10n/blob/master/scripts/extract_strings.sh

We will try to use the `compendium` feature to use smart overwrite.

**Comment by vladikoff** [comment]
And maybe also support sr to sr_latn conversion. @shane-tomlinson do you remember how to do that?

**Comment by rfk** [comment]
> And maybe also support sr to sr_latn conversion

More details via link thread in https://github.com/mozilla/fxa-content-server-l10n/issues/82

**Comment by vladikoff** [comment]
Closed in favour of https://github.com/mozilla/fxa-content-server-l10n/issues/91
