### ISSUE TITLE
Remove `pt` from the repo

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server-l10n#84]
If we are going to copy `pt_PT` to `pt`, it does not make sense to keep `pt` in this repo and have a potential contributor start unwittingly doing the translations for it.

Ref #81, https://github.com/mozilla/fxa-content-server/pull/3224.

@mathjazz, @rfk

**Comment by vladikoff** [comment]
We cannot remove "pt", it is the default setting when you download https://www.mozilla.org/pt-PT/firefox/new/

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server-l10n/issues/81#issuecomment-153779750

**Comment by shane-tomlinson** [comment]
For the record, the idea was, since we are already copying pt-PT to pt, remove pt from the repo so that we do not introduce discrepancies between pt and pt-PT.
