### ISSUE TITLE
Push all Romanian strings into production

### ISSUE THREAD

**Issue by cristisilaghi** [mozilla/fxa-content-server-l10n#89]
Hi. It seems some strings are not pushed into production, even if they were translated 15 days ago (and made few changes today on Pontoon).
Do we need a manual intervention for this or do we need to wait more for an automatic update?

**Comment by jrgm** [comment]
The current git sha in production is 5d5c2e032ff364674b7a05db6125fe60f72003da, which is from Oct 25th. So, changes in locale `ro` before that should be in production. Is there an example of a string that you would expect to be visible in production that is not so I can track down? What is the Accept-Language header your browser (or other tool) is sending (just for future reference)?

**Comment by rfk** [comment]
I see changes to Romanian on Nov 3rd (9fbaac82b929440c3ddf541a85a3e2d9df1ee645) and Oct 30th (34fe464ade6107201f131d3a8fa681e6592f18f0, 34c9184a0f3ea43d6bdc222dc35a2821df141c) which will go to production in the next release.  Anything earlier than those *should* be live already, but please point them out if that doesn't seem to be the case.

> Do we need a manual intervention for this or do we need to wait more for an automatic update?

FYI we generally deploy FxA every two weeks, picking up the latest translations available at that time.

**Comment by cristisilaghi** [comment]
@rfk @jrgm For example "A device began syncing with the devices connected to your Firefox Account."
Received yesterday an e-mail with mixed Romanian-English, but all the messages should be in Romanian.
That string is actually translated before Fx 42 release (commit from Octomber 20; ~16 days ago). :/ And is not the only string, I translated the rest of strings in Octomber 20. :/

**Comment by cristisilaghi** [comment]
![proof1](https://cloud.githubusercontent.com/assets/2406819/10939672/f76debc0-830b-11e5-8f79-373a5d62d330.png)

**Comment by jrgm** [comment]
Ah, sorry. For unrelated technical reasons, the server that sends the email had to be rolled back to an earlier version that contains older translations. We'll be updating to a new version next week.

**Comment by vladikoff** [comment]
If it is just that email then it is because we had to rollback our servers. Let us know if some other translation are old.
