### ISSUE TITLE
Add a right_before_production_deploy_script to copy locales

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server-l10n#91]
This script will do all the copying and should run right before prod deploy to get the most translations.
This is a bit of opposite to the "extract_strings", that one runs right after prod is built.

- [ ] Automatically copy/symlink "pt-PT" to "pt" https://github.com/mozilla/fxa-content-server-l10n/issues/81
- [ ] We might need to copy `hi-IN` to `hi`
- [ ] `sv_SE` => `sv`
- [ ] Remove all existing copy task in content-server  https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/copy.js#L86 and copy them as part of this script

**Comment by vladikoff** [comment]
@shane-tomlinson did I miss anything?

**Comment by vladikoff** [comment]
@shane-tomlinson the goal of this new script is to address the concern we had in the meeting where the "copied" locales (such as `hn` will only be copied after we run `extract_strings`). that is why this script run right before prod is built.

**Comment by shane-tomlinson** [comment]
@vladikoff - this seems like the correct approach to me. For completeness, you might want to add `sv_SE`=>`sv` too. Should `hi_IN`=>`hn` be `hi_IN`=>`hi`?

**Comment by vladikoff** [comment]
> @vladikoff - this seems like the correct approach to me. For completeness, you might want to add sv_SE=>sv too. Should hi_IN=>hn be hi_IN=>hi?

Perfect, thanks.
